units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
  # promicro-area
  chip_w: (kx*0.5) + 23
points:
  zones:
    matrix:
      anchor:
        shift: [150, -150] # [175, -90] 
      key:
        spread: px-2.8
        padding: py-1.8
      columns:
        outer:
          rows.mod.skip: true
        pinky:
          key:
        ring:
          key.stagger: ky * 0.4
        middle:
          key:
            stagger: ky * .17
        index:
          key:
            stagger: -(ky * 0.17)
        inner:
          rows.mod.skip: true
          key:
            stagger: -(ky * 0.17)
      rows:
        bottom:
        home:
        top:
    mod:
      key:
        padding: 20
        spread: 20
      anchor:
        ref: matrix_ring_bottom
        shift: [kx*0.5, -21]
      columns:
        opt:
        ctrl:
          key:
            splay: -5
            shift: [1, -1]
        layer:
          key:
            splay: -6
            shift: [2, -2]
        space:
          key:
            splay: -9
            width: 1.5kx
            rotate: 90
            shift: [5, -1]
        layer2:
          key:
            width: 1.5kx
            rotate: 90
            #splay: -10
            shift: [5, -13]
      rows:
        cluster:
          #shift: [2.6kx, -15]
          #splay: -10
          #spread: 25
  # rotate: -15
  # mirror: &mirror
  #   ref: matrix_inner_top
  #   distance: 4kx

outlines:
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx, ky]

  plate:
    - what: polygon
      operation: stack
      fillet: 4 # <---- rounded edges
      points:
        # upper-left corner
        - ref: matrix_outer_top
          shift: [-0.5px, 0.5py]

        # upper-mid
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [0.5px, 0.5py]

        # upper-right corner
        - ref: matrix_inner_top
          shift: [chip_w, 0.5py]

        # bottom-right corner
        - ref: matrix_inner_bottom
          shift: [chip_w, 0.5py]
        - ref: matrix_inner_bottom
          shift: [chip_w, -5]
        - ref: mod_space_cluster
          shift: [0.75px, 0]
        - ref: mod_space_cluster
          shift: [0.75px, -0.5py]
        - ref: mod_layer2_cluster
          shift: [0.75px, 0]
        - ref: mod_layer2_cluster
          shift: [0.75px, -.5py]
        - ref: mod_layer2_cluster
          shift: [-0.75px, -.5py]
        - ref: mod_layer2_cluster
          shift: [-0.75px, .5py]
        - ref: mod_space_cluster
          shift: [-0.75px, 0]
        - ref: mod_space_cluster
          shift: [-0.75px, .5py]

        # bottom-mid 
        - ref: mod_layer_cluster
          shift: [0, -0.55py]
        - ref: mod_ctrl_cluster
          shift: [0, -0.55py]
        - ref: mod_opt_cluster
          shift: [-0.5px, -0.55py]
        
        # bottom-left corner
        - ref: matrix_outer_bottom
          shift: [-0.5px, -0.5py]

# NOTE: this is the right plate outline. 
# Uncomment if needed. If you do, remember to uncomment
# the mirror section in points

  # plate_right:
  #   - what: polygon
  #     operation: stack
  #     fillet: 4 # <---- rounded edges
  #     points:
  #       # upper-left corner
  #       - ref: mirror_matrix_outer_top
  #         shift: [-0.5px, 0.5py]
  #
  #       # upper-mid
  #       - ref: mirror_matrix_ring_top
  #         shift: [-0.5px, 0.5py]
  #       - ref: mirror_matrix_middle_top
  #         shift: [-0.5px, 0.5py]
  #       - ref: mirror_matrix_middle_top
  #         shift: [0.5px, 0.5py]
  #
  #       # upper-right corner
  #       - ref: mirror_matrix_inner_top
  #         shift: [chip_w, 0.5py]
  #
  #       # bottom-right corner
  #       - ref: mirror_matrix_inner_bottom
  #         shift: [chip_w, 0.5py]
  #       - ref: mirror_matrix_inner_bottom
  #         shift: [chip_w, -5]
  #       - ref: mirror_mod_space_cluster
  #         shift: [0.75px, 0]
  #       - ref: mirror_mod_space_cluster
  #         shift: [0.75px, -0.5py]
  #       - ref: mirror_mod_layer2_cluster
  #         shift: [0.75px, 0]
  #       - ref: mirror_mod_layer2_cluster
  #         shift: [0.75px, -.5py]
  #       - ref: mirror_mod_layer2_cluster
  #         shift: [-0.75px, -.5py]
  #       - ref: mirror_mod_layer2_cluster
  #         shift: [-0.75px, .5py]
  #       - ref: mirror_mod_space_cluster
  #         shift: [-0.75px, 0]
  #       - ref: mirror_mod_space_cluster
  #         shift: [-0.75px, .5py]
  #
  #       # bottom-mid 
  #       - ref: mirror_mod_layer_cluster
  #         shift: [0, -0.55py]
  #       - ref: mirror_mod_ctrl_cluster
  #         shift: [0, -0.55py]
  #       - ref: mirror_mod_opt_cluster
  #         shift: [-0.5px, -0.55py]
  #       
  #       # bottom-left corner
  #       - ref: mirror_matrix_outer_bottom
  #         shift: [-0.5px, -0.5py]

  combo:
    - name: plate
    - operation: subtract
      name: keys

pcbs:
  keybear:
    outlines:
      main:
        outline: plate
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          rotate: 270
          shift: [kx*0.45, 1.6]
      # rgb:
      #   what: rgb
      #   where: true
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: matrix_inner_top
          rotate: -90
          shift: [px*0.95, -0.3*py]
      # pcm12:
      #   what: pcm12
      #   where:
      #     ref: matrix_inner_bottom
      #     shift: [5, 5]
      #   params:
      #     reverse: true
      #     from: "{{colrow}}"
      #     to: "{{row_net}}"
