units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
points:
  zones:
    matrix:
      key:
        padding: 19
        spread: 19
      columns:
        outer:
          rows.mod.skip: true
        pinky:
          key:
        ring:
          key.stagger: ky * 0.4
        middle:
          key:
            stagger: ky * .17
        index:
          key:
            stagger: -(ky * 0.17)
        inner:
          rows.mod.skip: true
          key:
            stagger: -(ky * 0.17)
      rows:
        #mod:
        bottom:
        home:
        top:
    mod:
      key:
        padding: 20
        spread: 20
      anchor:
        ref: matrix_ring_bottom
        shift: [kx*0.5, -21]
      columns:
        opt:
        ctrl:
          key:
            splay: -5
            shift: [1, -1]
        layer:
          key:
            splay: -6
            shift: [2, -2]
        space:
          key:
            splay: -9
            height: 1.5kx
            shift: [5, -1]
        layer2:
          key:
            height: 1.5kx
            #splay: -10
            shift: [5, -13]
      rows:
        cluster:
          #shift: [2.6kx, -15]
          #splay: -10
          #spread: 25
  rotate: -15
  #mirror: &mirror
  #  ref: matrix_inner_top
  #  distance: 4kx

outlines:
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx, ky]
  plate:
    - what: polygon
      operation: stack
      fillet: 3
      points:
        # upper-left corner
        - ref: matrix_outer_top
          shift: [-0.5px, 0.5py]

        # upper-mid
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [0.5px, 0.5py]

        # upper-right corner
        - ref: matrix_inner_top
          shift: [0.5px, 0.5py]
        
        # bottom-right corner
        - ref: matrix_inner_bottom
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_bottom
          shift: [0.5px, -4]
        - ref: mod_space_cluster
          shift: [0, 0.75py]
        - ref: mod_space_cluster
          shift: [0.5px, 0.75py]
        - ref: mod_layer2_cluster
          shift: [0.5px, 0.75py]
        - ref: mod_layer2_cluster
          shift: [0.5px, -0.75py]
        - ref: mod_layer2_cluster
          shift: [-0.5px, -0.75py]
        - ref: mod_space_cluster
          shift: [-0.5px, -0.75py]

        # bottom-mid 
        - ref: mod_opt_cluster
          shift: [-0.5px, -0.5py]
        
        # bottom-left corner
        - ref: matrix_outer_bottom
          shift: [-0.5px, -0.5py]
  combo:
    - name: plate
    - operation: subtract
      name: keys
